remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Hadamard and S Matrix Library]
description: [This site serves as a recurring library of examples of all known orders of Hadamard and S matrices.]
