remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme 
show_downloads: true
title: [Hadamard and S Matrix Library]
description: [This site serves as a virtual library of examples of all known orders of Hadamard and S matrices.]


